version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: db_pisos
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring